First-playbook.yml

---
- name: My First Playbook
  hosts: webservers
  become: true
  tasks:

  - name: Install apache httpd
    apt:
      name: apache2
      state: absent

---------------------------------------------------------------------------------------------------------------------------
Pentest.yml

---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:

  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa                                                                               
      state: started
      restart_policy: always
      published_ports: 80:80

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes
---------------------------------------------------------------------------------------------------------------------------
Filebeat-playbook.yml

---
- name: Installing at Launch Filebeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

  - name: Install filebeat .deb
    command: sudo dpkg -i filebeat-7.6.1-amd64.deb

  - name: Drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable and Configure system Module
    command: filebeat modules enable system

  - name: Setup filebeat
    command: filebeat setup

  - name: Start filebeat service
    command: service filebeat start

---------------------------------------------------------------------------------------------------------------------------
Metricbeat-playbook.yml

---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:
    # Use command module
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.d$
    # Use command module
  - name: install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

    # Use copy module
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Use command module
  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker

    # Use command module
  - name: setup metric beat
    command: metricbeat setup

    # Use command module 
  - name: start metric beat
    command: service metricbeat start

    # Use systemd module
  - name: Enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes    
---------------------------------------------------------------------------------------------------------------------------
Elk.yml

---
 - name: configure Elk VM with Docker
   hosts: elkservers
   remote_user: RedAdmin
   become: true
   tasks:
     - name: Install docker.io
       apt:
         update_cache: yes
         name: docker.io
         state: present

     - name: install pip3
       apt:
         force_apt_get: yes
         name: python3-pip
         state: present

     - name: Install Docker python module
       pip:
         name: docker
         state: present

     - name: Use more memory
       sysctl:
         name: vm.max_map_count
         value: "262144"

    - name: download and launch a docker elk container
       docker_container:
         name: elk
         image: sebp/elk:761
         state: started
         restart_policy: always
         published_ports:
           - 5601:5601
           - 9200:9200
           - 5044:5044
---------------------------------------------------------------------------------------------------------------------------